/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src.gui;

/**
 *
 * @author Emili
 */
public abstract class PanelMesaGui extends javax.swing.JPanel {

    /**
     * Creates new form PanelMesa
     */
    public PanelMesaGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jPanelTop = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelIdOrdenTag = new javax.swing.JLabel();
        jLabelIdOrden = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jLabelIdOrdenTag1 = new javax.swing.JLabel();
        jLabelIdOrden1 = new javax.swing.JLabel();
        jPanelButtons = new javax.swing.JPanel();
        jButtonCerrarMesa = new javax.swing.JButton();
        jButtonCobrar = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jButtonAbrir = new javax.swing.JButton();
        jPanelCenter = new javax.swing.JPanel();
        jPanelCenterLeft = new javax.swing.JPanel();
        jPanelTablaProductos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jButtonInicio = new javax.swing.JButton();
        jPanelCategoriasBtns = new javax.swing.JPanel();
        jButtonCat0 = new javax.swing.JButton();
        jButtonCat2 = new javax.swing.JButton();
        jButtonCat4 = new javax.swing.JButton();
        jButtonCat6 = new javax.swing.JButton();
        jButtonCat7 = new javax.swing.JButton();
        jButtonCat5 = new javax.swing.JButton();
        jButtonCat3 = new javax.swing.JButton();
        jButtonCat1 = new javax.swing.JButton();
        jPanelCenterRight = new javax.swing.JPanel();
        jPanelTablaServidos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableServidos = new javax.swing.JTable();
        jPanelCenterBtns = new javax.swing.JPanel();
        jButtonQuitar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jButtonLimpiarCuenta = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(0, 0));

        jPanelMain.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanelTop.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelTitle.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("<Nombre Mesa>");
        jLabelTitle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabelIdOrdenTag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIdOrdenTag.setText("idOrden: ");

        jLabelIdOrden.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelIdOrden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIdOrden.setText("<0000>");

        jLabelEstado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEstado.setText("<estado>");

        jLabelIdOrdenTag1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIdOrdenTag1.setText("Total:");

        jLabelIdOrden1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelIdOrden1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIdOrden1.setText("<0000>");

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelIdOrdenTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelIdOrden, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelIdOrdenTag1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelIdOrden1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelTopLayout.setVerticalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTopLayout.createSequentialGroup()
                        .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTopLayout.createSequentialGroup()
                        .addComponent(jLabelIdOrdenTag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelIdOrden))
                    .addGroup(jPanelTopLayout.createSequentialGroup()
                        .addComponent(jLabelIdOrdenTag1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelIdOrden1)))
                .addContainerGap())
        );

        jLabelTitle.getAccessibleContext().setAccessibleDescription("");
        jLabelIdOrden.getAccessibleContext().setAccessibleDescription("");
        jLabelEstado.getAccessibleContext().setAccessibleDescription("");

        jButtonCerrarMesa.setText("<html><p style=\"text-align:center;\">CERRAR<br>MESA</p></html>");
        jButtonCerrarMesa.setPreferredSize(new java.awt.Dimension(100, 40));

        jButtonCobrar.setText("COBRAR");
        jButtonCobrar.setPreferredSize(new java.awt.Dimension(100, 40));

        jButtonBack.setText("VOLVER");
        jButtonBack.setPreferredSize(new java.awt.Dimension(100, 40));

        jButtonAbrir.setText("ABRIR");
        jButtonAbrir.setPreferredSize(new java.awt.Dimension(100, 40));

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonBack, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAbrir, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCobrar, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCerrarMesa, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCerrarMesa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(jButtonCobrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAbrir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelButtonsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonAbrir, jButtonBack, jButtonCerrarMesa, jButtonCobrar});

        jButtonCerrarMesa.getAccessibleContext().setAccessibleDescription("");
        jButtonCobrar.getAccessibleContext().setAccessibleDescription("");
        jButtonBack.getAccessibleContext().setAccessibleDescription("");
        jButtonAbrir.getAccessibleContext().setAccessibleDescription("");

        jPanelCenterLeft.setMinimumSize(new java.awt.Dimension(198, 240));

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableProductos);
        jTableProductos.getAccessibleContext().setAccessibleDescription("");

        jButtonInicio.setText("Inicio");

        javax.swing.GroupLayout jPanelTablaProductosLayout = new javax.swing.GroupLayout(jPanelTablaProductos);
        jPanelTablaProductos.setLayout(jPanelTablaProductosLayout);
        jPanelTablaProductosLayout.setHorizontalGroup(
            jPanelTablaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTablaProductosLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelTablaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelTablaProductosLayout.setVerticalGroup(
            jPanelTablaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTablaProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonInicio.getAccessibleContext().setAccessibleDescription("");

        jButtonCat0.setText("Bebidas");
        jButtonCat0.setMinimumSize(new java.awt.Dimension(90, 0));
        jButtonCat0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCat1ActionPerformed(evt);
            }
        });

        jButtonCat2.setText("Aperitivos");
        jButtonCat2.setMinimumSize(new java.awt.Dimension(90, 0));
        jButtonCat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCat1ActionPerformed(evt);
            }
        });

        jButtonCat4.setText("Menus");
        jButtonCat4.setMinimumSize(new java.awt.Dimension(90, 0));

        jButtonCat6.setText("Postres");
        jButtonCat6.setMinimumSize(new java.awt.Dimension(90, 0));

        jButtonCat7.setText("Cafes");
        jButtonCat7.setMinimumSize(new java.awt.Dimension(90, 0));
        jButtonCat7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCat1ActionPerformed(evt);
            }
        });

        jButtonCat5.setText("Comidas");
        jButtonCat5.setMinimumSize(new java.awt.Dimension(90, 0));
        jButtonCat5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCat1ActionPerformed(evt);
            }
        });

        jButtonCat3.setText("Tapas");
        jButtonCat3.setMinimumSize(new java.awt.Dimension(90, 0));
        jButtonCat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCat1ActionPerformed(evt);
            }
        });

        jButtonCat1.setText("Alcohol");
        jButtonCat1.setMinimumSize(new java.awt.Dimension(90, 0));

        javax.swing.GroupLayout jPanelCategoriasBtnsLayout = new javax.swing.GroupLayout(jPanelCategoriasBtns);
        jPanelCategoriasBtns.setLayout(jPanelCategoriasBtnsLayout);
        jPanelCategoriasBtnsLayout.setHorizontalGroup(
            jPanelCategoriasBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategoriasBtnsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCategoriasBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonCat4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCat2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCat0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCat6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCategoriasBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCat1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCat5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCat3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCat7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCategoriasBtnsLayout.setVerticalGroup(
            jPanelCategoriasBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategoriasBtnsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCategoriasBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCat0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCat1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCategoriasBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCat2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCat3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCategoriasBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCat4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCat5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCategoriasBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCat6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCat7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButtonCat0.getAccessibleContext().setAccessibleDescription("");
        jButtonCat2.getAccessibleContext().setAccessibleDescription("");
        jButtonCat4.getAccessibleContext().setAccessibleDescription("");
        jButtonCat6.getAccessibleContext().setAccessibleDescription("");
        jButtonCat7.getAccessibleContext().setAccessibleDescription("");
        jButtonCat5.getAccessibleContext().setAccessibleDescription("");
        jButtonCat3.getAccessibleContext().setAccessibleDescription("");
        jButtonCat1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPanelCenterLeftLayout = new javax.swing.GroupLayout(jPanelCenterLeft);
        jPanelCenterLeft.setLayout(jPanelCenterLeftLayout);
        jPanelCenterLeftLayout.setHorizontalGroup(
            jPanelCenterLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTablaProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelCategoriasBtns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelCenterLeftLayout.setVerticalGroup(
            jPanelCenterLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTablaProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelCategoriasBtns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelCenterRight.setMinimumSize(new java.awt.Dimension(198, 240));
        jPanelCenterRight.setPreferredSize(new java.awt.Dimension(198, 240));

        jTableServidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableServidos);
        jTableServidos.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPanelTablaServidosLayout = new javax.swing.GroupLayout(jPanelTablaServidos);
        jPanelTablaServidos.setLayout(jPanelTablaServidosLayout);
        jPanelTablaServidosLayout.setHorizontalGroup(
            jPanelTablaServidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelTablaServidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelTablaServidosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelTablaServidosLayout.setVerticalGroup(
            jPanelTablaServidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelTablaServidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelTablaServidosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanelCenterRightLayout = new javax.swing.GroupLayout(jPanelCenterRight);
        jPanelCenterRight.setLayout(jPanelCenterRightLayout);
        jPanelCenterRightLayout.setHorizontalGroup(
            jPanelCenterRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTablaServidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelCenterRightLayout.setVerticalGroup(
            jPanelCenterRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTablaServidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButtonQuitar.setText("Quitar");

        jButtonAgregar.setText("Agregar");

        jButtonLimpiarCuenta.setText("<html><p style=\"text-align:center;\">Limpiar<br>Cuenta</p></html>");

        javax.swing.GroupLayout jPanelCenterBtnsLayout = new javax.swing.GroupLayout(jPanelCenterBtns);
        jPanelCenterBtns.setLayout(jPanelCenterBtnsLayout);
        jPanelCenterBtnsLayout.setHorizontalGroup(
            jPanelCenterBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCenterBtnsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCenterBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonQuitar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAgregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLimpiarCuenta))
                .addContainerGap())
        );

        jPanelCenterBtnsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAgregar, jButtonLimpiarCuenta, jButtonQuitar});

        jPanelCenterBtnsLayout.setVerticalGroup(
            jPanelCenterBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenterBtnsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jButtonLimpiarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelCenterBtnsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonAgregar, jButtonQuitar});

        jButtonQuitar.getAccessibleContext().setAccessibleDescription("");
        jButtonAgregar.getAccessibleContext().setAccessibleDescription("");
        jButtonLimpiarCuenta.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPanelCenterLayout = new javax.swing.GroupLayout(jPanelCenter);
        jPanelCenter.setLayout(jPanelCenterLayout);
        jPanelCenterLayout.setHorizontalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCenterLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanelCenterBtns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCenterRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCenterLayout.setVerticalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenterLayout.createSequentialGroup()
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCenterBtns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCenterLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCenterRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCat1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton jButtonAbrir;
    protected javax.swing.JButton jButtonAgregar;
    protected javax.swing.JButton jButtonBack;
    protected javax.swing.JButton jButtonCat0;
    protected javax.swing.JButton jButtonCat1;
    protected javax.swing.JButton jButtonCat2;
    protected javax.swing.JButton jButtonCat3;
    protected javax.swing.JButton jButtonCat4;
    protected javax.swing.JButton jButtonCat5;
    protected javax.swing.JButton jButtonCat6;
    protected javax.swing.JButton jButtonCat7;
    protected javax.swing.JButton jButtonCerrarMesa;
    protected javax.swing.JButton jButtonCobrar;
    protected javax.swing.JButton jButtonInicio;
    protected javax.swing.JButton jButtonLimpiarCuenta;
    protected javax.swing.JButton jButtonQuitar;
    protected javax.swing.JLabel jLabelEstado;
    protected javax.swing.JLabel jLabelIdOrden;
    protected javax.swing.JLabel jLabelIdOrden1;
    private javax.swing.JLabel jLabelIdOrdenTag;
    private javax.swing.JLabel jLabelIdOrdenTag1;
    protected javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelButtons;
    protected javax.swing.JPanel jPanelCategoriasBtns;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelCenterBtns;
    protected javax.swing.JPanel jPanelCenterLeft;
    private javax.swing.JPanel jPanelCenterRight;
    private javax.swing.JPanel jPanelMain;
    protected javax.swing.JPanel jPanelTablaProductos;
    private javax.swing.JPanel jPanelTablaServidos;
    protected javax.swing.JPanel jPanelTop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    protected javax.swing.JTable jTableProductos;
    protected javax.swing.JTable jTableServidos;
    // End of variables declaration//GEN-END:variables
}
