/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  NarF
 * Created: Jun 1, 2019
 */

INSERT INTO mesas VALUES( 1, 'Mesa 1',    4, 0),
                        ( 2, 'Mesa 2',    4, 0),
                        ( 3, 'Mesa 3',    2, 0),
                        ( 4, 'Mesa 4',    2, 0),
                        ( 5, 'Mesa 5',    4, 0),
                        ( 6, 'Mesa 6',    4, 0),
                        ( 7, 'Mesa 7',    6, 0),
                        ( 8, 'Mesa 8',    6, 0),
                        ( 9, 'Barra 1',   2, 0),
                        (10, 'Barra 2',   2, 0),
                        (11, 'Barra 3',   2, 0),
                        (12, 'Barra 4',   2, 0),
                        (13, 'Terraza 1', 4, 0),
                        (14, 'Terraza 2', 4, 0),
                        (15, 'Terraza 3', 8, 0),
                        (16, 'Terraza 4', 8, 0),
                        (17, 'Extra 1',    4, 0),
                        (18, 'Extra 2',    4, 0),
                        (19, 'Extra 3',    2, 0),
                        (20, 'Extra 4',    2, 0),
                        (21, 'Extra 5',    4, 0),
                        (22, 'Extra 6',    4, 0);

INSERT INTO categorias VALUES(1, 'Bebidas'),
                             (2, 'Alcohol'),
                             (3, 'Aperitivos'),
                             (4, 'Tapas'),
                             (5, 'Menus'),
                             (6, 'Comidas'),
                             (7, 'Postres'),
                             (8, 'Cafes'),
                             (9, 'Descatalogados');

INSERT INTO productos VALUES( 1, 'Agua Mineral', 1.50, 1),
                            ( 2, 'CocaCola', 2.50, 1),
                            ( 3, 'CocaCola-Zero', 2.50, 1),
                            ( 4, 'CocaCola-Light', 2.50, 1),
                            ( 5, 'CocaCola-ZeroZero', 2.50, 1),
                            ( 6, 'KAS Naranja', 2.50, 1),
                            ( 7, 'KAS Limon', 2.50, 1),
                            ( 8, 'Nestea', 2.50, 1),
                            ( 9, 'Sprite', 2.50, 1),
                            ( 10, 'Agua Gas', 2.00, 1),
                            ( 11, 'Tonica', 2.50, 1),
                            ( 12, 'Zumo Melocoton', 2.30, 1),
                            ( 13, 'Zumo Piña', 2.30, 1),
                            ( 14, 'Zumo Naranja', 2.30, 1),
                            ( 15, 'Aquarius Limon', 2.50, 1),
                            ( 16, 'Aquarius Naranja', 2.50, 1),
                            ( 17, 'Bitter', 2.00, 1),
                            ( 18, 'Copa Vino Tinto', 2.30, 2),
                            ( 19, 'Copa Vino Blanco', 2.30, 2),
                            ( 20, 'Cerveza', 2.00, 2),
                            ( 21, 'Cerveza Especial', 2.30, 2),
                            ( 22, 'Cerveza 0/0', 2.00, 2),
                            ( 23, 'Cerveza Sin Gluten', 2.30, 2),
                            ( 24, 'Cerveza Negra', 2.40, 2),
                            ( 25, 'Sidra Dulce', 2.30, 2),
                            ( 26, 'Sidra Fresa', 2.30, 2),
                            ( 27, 'Tinto de Verano', 3.75, 2),
                            ( 28, 'Sangria', 3.75, 2),
                            ( 29, 'Cuba Libre', 5.75, 2),
                            ( 30, 'GinTonic', 5.75, 2),
                            ( 31, 'Destornillador', 5.75, 2),
                            ( 32, 'Piña Colada', 6.50, 2),
                            ( 33, 'Mojito', 6.50, 2),                     
                            ( 34, 'Nachos', 1.00, 3),
                            (35, 'Patatillas', 1.00, 3),
                            (36, 'Pipas Saladas', 1.00, 3),
                            (37, 'Aceitunas', 1.00, 3),
                            (38, 'Cacahuetes', 1.00, 3),
                            (39, 'Barra de Muesli', 1.00, 3),
                            (40, 'Tabla de Quesos y Pates', 12.25, 4),
                            (41, 'Tabla de Quesos', 8.25, 4),
                            (42, 'Porcion de  Pizza', 3.25, 4),
                            (43, 'Porcion de Empanada', 3.25, 4),
                            (44, 'Crujientes de Langostinos', 12.25, 4),
                            (45, 'Croquetas Variadas', 6.50, 4),
                            (46, 'Croquetas de Jamon', 6.50, 4),
                            (47, 'Croquetas de Chorizo', 6.50, 4),
                            (48, 'Croquetas de Espinaca', 6.50, 4),
                            (49, 'Croquetas de Zanahoria', 6.50, 4),
                            (50, 'Chipirones', 10.00, 4),
                            (51, 'Calamares', 10.05, 4),
                            (52, 'Boquerones Vinagreta', 6.50, 4),
                            (53, 'Mejillones Escabeche', 5.50, 4),
                            (54, 'Menu 1 personas', 11.25, 5),
                            (55, 'Menu 2 personas', 20.00, 5),
                            (56, 'Menu 3 personas', 30.00, 5),
                            (57, 'Menu 4 Personas', 38.50, 5),
                            (58, 'Clubhouse sandwich', 8.50, 6),
                            (59, 'Granjero de Pollo', 7.50, 6),
                            (60, 'Milanesa de Ternera', 9.50, 6),
                            (61, 'Pechuga a la Plancha', 8.50, 6),
                            (62, 'Croca de Ternera', 14.50, 6),
                            (63, 'Picaña', 17.50, 6),
                            (64, 'Costillas de Cerdo BBQ', 14.00, 6),
                            (65, 'Secreto Iberico', 12.50, 6),
                            (66, 'Pulpo a la Plancha', 18.50, 6),
                            (67, 'Arroz Marinera', 27.50, 6),
                            (68, 'Risotto de Setas', 18.00, 6),
                            (69, 'Risotto de Gambas', 18.50, 6),
                            (70, 'Hamburguesa de Ternera', 8.50, 6),
                            (71, 'Hamburguesa de Pollo', 7.50, 6),
                            (72, 'Bola de Helado', 2.50, 7),
                            (73, 'Brownie', 3.50, 7),
                            (74, 'Cañita de Crema', 2.50, 7),
                            (75, 'Tarta de Chocolate', 3.75, 7),
                            (76, 'Tarta de Manzana', 3.75, 7),
                            (77, 'Tarta de Zanahoria', 3.75, 7),
                            (78, 'Tarta de Profiteroles', 3.75, 7),
                            (79, 'Mus de Chocolate', 3.25, 7),
                            (80, 'Mus de Vainilla', 3.25, 7),
                            (81, 'Crema de Yogurt', 5.50, 7),
                            (82, 'Natilla de la Abuela', 5.50, 7),
                            (83, 'Banana Split', 7.50, 7),
                            (84, 'Solo', 1.20, 8),
                            (85, 'Solo Largo', 1.20, 8),
                            (86, 'Cortado', 1.20, 8),
                            (87, 'Con Leche', 1.50, 8),
                            (88, 'Manchado', 1.50, 8),
                            (89, 'Capuccino', 2.20, 8),
                            (90, 'Zamburiñas', 15.25, 9),
                            (91, 'Paleta de Helado', 2.50, 9),
                            (92, 'Pipas', 1.75, 9);