/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src.gui.template;

/**
 *
 * @author NarF
 */
public class MenuModel extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MenuModel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuInicio = new javax.swing.JMenu();
        jMenuItemNueva = new javax.swing.JMenuItem();
        jMenuItemCargar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuVer = new javax.swing.JMenu();
        jMenuItemMesas = new javax.swing.JMenuItem();
        jMenuItemCocina = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuEditar = new javax.swing.JMenu();
        jMenuItemEditMesas = new javax.swing.JMenuItem();
        jMenuItemEditProductos = new javax.swing.JMenuItem();
        jMenuItemCategorias = new javax.swing.JMenuItem();
        jMenuMas = new javax.swing.JMenu();
        jMenuItemInformacion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuInicio.setText("Inicio");

        jMenuItemNueva.setText("Nueva");
        jMenuInicio.add(jMenuItemNueva);

        jMenuItemCargar.setText("Cargar");
        jMenuInicio.add(jMenuItemCargar);
        jMenuInicio.add(jSeparator1);

        jMenuItemSalir.setText("Salir");
        jMenuInicio.add(jMenuItemSalir);

        jMenuBar1.add(jMenuInicio);

        jMenuVer.setText("Ver");
        jMenuVer.setEnabled(false);

        jMenuItemMesas.setText("Mesas");
        jMenuVer.add(jMenuItemMesas);

        jMenuItemCocina.setText("Cocina");
        jMenuVer.add(jMenuItemCocina);
        jMenuVer.add(jSeparator2);

        jMenuEditar.setText("Editar");

        jMenuItemEditMesas.setText("Mesas");
        jMenuEditar.add(jMenuItemEditMesas);

        jMenuItemEditProductos.setText("Productos");
        jMenuEditar.add(jMenuItemEditProductos);

        jMenuItemCategorias.setText("Categorias");
        jMenuEditar.add(jMenuItemCategorias);

        jMenuVer.add(jMenuEditar);

        jMenuBar1.add(jMenuVer);

        jMenuMas.setText("Mas");

        jMenuItemInformacion.setText("Informacion");
        jMenuMas.add(jMenuItemInformacion);

        jMenuBar1.add(jMenuMas);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuModel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenu jMenuInicio;
    private javax.swing.JMenuItem jMenuItemCargar;
    private javax.swing.JMenuItem jMenuItemCategorias;
    private javax.swing.JMenuItem jMenuItemCocina;
    private javax.swing.JMenuItem jMenuItemEditMesas;
    private javax.swing.JMenuItem jMenuItemEditProductos;
    private javax.swing.JMenuItem jMenuItemInformacion;
    private javax.swing.JMenuItem jMenuItemMesas;
    private javax.swing.JMenuItem jMenuItemNueva;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenu jMenuMas;
    private javax.swing.JMenu jMenuVer;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
